site:
  lang: ru
  title: Мой Блогъ 2.0
  created: 2011-07-21
  description: Blog description
author:
  name: ChessMax
  github: https://github.com/ChessMax
output: ./public
viewEngine:
  name: vash
#  views: ''
  config:
    htmlEscape: false
#    settings:
#      views: ./theme


source:
  - ./source/posts/*.md
  - ./source/other_posts/*.md
