title: Мой Блогъ 2.0
author:
  name: ChessMax
  github: https://github.com/ChessMax
output: ./public
viewEngine:
  name: vash
  config:
    htmlEscape: false

source:
  - ./source/posts/*.md
  - ./source/other_posts/*.md
