theme: ./theme
source: ./source/
output: ./public
viewEngine:
  name: vash
  views: ./theme
  config:
    htmlEscape: false
server:
  port: 3000
  webSocketPort: 9000
  hotReload: true
staticFiles:
  patterns:
    - '**/*.css'
    - '**/*.svg'
    - '**/*.png'
